[package]
name = "cratup_tree_sitter"
version = "0.2.0"
edition = "2024"

[dependencies]
derive_more = { version = "2", features = ["full"] }
semver = "1.0.26"
thiserror = "2.0.12"
tree-sitter = "0.20.0"
tree-sitter-toml = "0.20.0"
log = "0.4"

# Optional, for building the grammar
[build-dependencies]
cc = "*"
